# Generated by Django 3.2.19 on 2023-05-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-10-18', help_text='Enter your birthdate', verbose_name='Date of Birth'),
        ),
    ]
